name: lantern-rustdesk

services:
  hbbs:
    image: ${RUSTDESK_SERVER_IMAGE:-rustdesk/rustdesk-server:1.1.15-amd64@sha256:696eeb859a7191e95eca697e5fbfffaaffa47dc4f8b339dad1a35312b7b6972e}
    command: hbbs -r ${LANTERN_CORE_IP:?Set LANTERN_CORE_IP}:21117
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/root
    depends_on:
      - hbbr

  hbbr:
    image: ${RUSTDESK_SERVER_IMAGE:-rustdesk/rustdesk-server:1.1.15-amd64@sha256:696eeb859a7191e95eca697e5fbfffaaffa47dc4f8b339dad1a35312b7b6972e}
    command: hbbr
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/root
