---
- Infrastructure:
    - DNS:
        href: http://dns.home.arpa/admin/
        description: Pi-hole
    - Status:
        href: http://status.home.arpa
        description: Uptime Kuma
    - Windows:
        href: ssh://windows.home.arpa
        description: Windows application host
- Applications:
    - Photos:
        href: http://photos.home.arpa
        description: Immich
